mlb_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'mlb') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'mlbpassword') }}"
      port: "{{ env_var('POSTGRES_PORT', '5433') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'mlb_pipeline') }}"
      schema: analytics
      threads: 4
